### ISSUE TITLE
Broken surface ID buffer on  GTX 1070 ?

### ISSUE THREAD

**Issue by OmarShehata** [OmarShehata/webgl-outlines#9]
Reported on Twitter: https://twitter.com/tamat/status/1580872701035495425

![image](https://user-images.githubusercontent.com/1711126/195929804-49cee196-119d-4ed0-b7a2-4b2203df8a35.png)

I haven't been able to reproduce. My guess is the surfaceID buffer has invalid data drawn to it. That buffer is of type `HalfFloat`. I picked that because I thought that'd have more support than `Float` buffers, but it may be the other way around? 

This buffer type is defined here:

https://github.com/OmarShehata/webgl-outlines/blob/b591487f9ae9c1fe450580be1f3b02cf58dd19d1/threejs-outlines-minimal/src/CustomOutlinePass.js#L28

**Comment by zalo** [comment]
I'm seeing this too on a 3080 in both Chrome and Firefox.   In the console, I'm seeing this shader error:
```
index.cedc7d4f.js:3113 THREE.WebGLProgram: Program Info Log: C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
```
On iOS Safari, it appears to work fine.

**Comment by OmarShehata** [comment]
Thanks @zalo ! Could I see what the "surfaceID debug buffer" looks like for you? And just to rule it out, the normal buffer and depth buffer modes as well?

**Comment by zalo** [comment]
![image](https://user-images.githubusercontent.com/174475/196299658-bf9d761c-4c88-4546-951b-362347af96f8.png)

Except for this buffer and the OutlinesV2 buffers, all the other buffer modes (including Outlines V1) look perfectly sane and correct.

**Comment by OmarShehata** [comment]
Interesting, yeah so the problem is definitely in how the surfaceIDs are drawn, but I'm not sure why. This is the shader that draws the surfaceID's:

https://github.com/OmarShehata/webgl-outlines/blob/main/threejs/src/FindSurfaces.js#L164

I normalize it to 0-1 before I draw in the red channel. The "debug draw" version where it assigns a random color based on the ID shader is here:

https://github.com/OmarShehata/webgl-outlines/blob/main/threejs/src/FindSurfaces.js#L185

**Comment by dtrebilco** [comment]
I also get this on Brave browser on a 3070

**Comment by OmarShehata** [comment]
For people who can reproduce, could I get a screenshot of your WebGL report (https://webglreport.com/) ?

**Comment by dtrebilco** [comment]
![Screenshot 2022-10-18 223141](https://user-images.githubusercontent.com/7506147/196430174-540dbda0-decd-41e9-95c4-4f4efc8951d5.jpg)
![Screenshot 2022-10-18 223209](https://user-images.githubusercontent.com/7506147/196430188-91e6c169-e9ac-4345-8f9f-8391c3ac4124.jpg)

**Comment by dtrebilco** [comment]
I think it might be caused by the GL_DITHER option that is enabled by default - this would mess up the index values being written to the color buffer and show edges everywhere. 
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/enable

If I can get your example running locally I'll try and add and test.

**Comment by dtrebilco** [comment]
OK I think I know what is causing this:

1) The object ID is read by the vertex shader (verified correct) and passed as a basic interpolator to the fragment shader.
2) The fragment shader basically just writes this object ID out to the Float16 buffer
3) Post process is applied on these id buffer values where if surfaceValueDiff != 0

As these id values are floating point, any slight variation will produce a outline. (in general, comparing floating point values for exact values causes problems)

There are 3 ways to fix it:
Solution 1) Don't compare against exact values - change to surfaceValueDiff > 0.01 - that seems to work 
Solution 2) Make sure no perspective correct interpolation is happening on the varying that will not need it - this ensures you get the exact value in the fragment shader - just put a "flat varying" in front of the shader interpolator.
Solution 3) Another way to prevent perspective correct interpolation is to make sure position "w" value is 1. Simply do a gl_Position /= gl_Position.w in the vertex shader. 

Side note: I think  you need to clamp the value "outline" when doing 

gl_FragColor = vec4(mix(sceneColor, outlineColor, outline));

as outline could be > 1.0

**Comment by OmarShehata** [comment]
Awesome, thank you so much @dtrebilco for digging into this and for the detailed solutions!! I should have guessed it was the interpolation, because this comes up in the original tweet thread where I first heard about this technique:

https://twitter.com/ianmaclarty/status/1499494985762480128

The solution suggested there is a simple `round(surfaceId)` which we should expect to work because we know the surfaceIds are always integers.

@dtrebilco could you give that a try and if that works you, would you like to open a PR to make this change? Clamping the outline value at the end also makes sense to me. 

Otherwise solution 3 sounds good to me since it doesn't require WebGL 2 and doesn't require setting a threshold to compare against. We can add a comment explaining why that's necessary/linking to this discussion.

**Comment by OmarShehata** [comment]
This is now fixed in https://github.com/OmarShehata/webgl-outlines/pull/10

I've updated the demo with the latest code, so that should look correct for everyone now: https://threejs-outlines-postprocess.glitch.me/

Thanks again @dtrebilco and everyone for the help here!

**Comment by dtrebilco** [comment]
Verified live demo looks correct for me
